### ISSUE TITLE
File object not working with Flutter Web

### ISSUE THREAD

**Issue by nasir447** [dint-dev/universal_io#16]
Error: UnimplementedError
    at Object.throw_ [as throw] (http://localhost:59940/dart_sdk.js:5334:11)
    at Function.fromRawPath (http://localhost:59940/packages/universal_io/src/io_impl_js/sync_socket.dart.lib.js:4873:17)
    at http://localhost:59940/packages/darat_admin/Screens/AddProject.dart.lib.js:7940:40
    at AddProject._AddProjectState.new.setState (http://localhost:59940/packages/flutter/src/widgets/widget_span.dart.lib.js:16616:22)
    at AddProject._AddProjectState.new.pickLogo (http://localhost:59940/packages/darat_admin/Screens/AddProject.dart.lib.js:7938:14)  
    at pickLogo.next (<anonymous>)
    at http://localhost:59940/dart_sdk.js:39032:33
    at _RootZone.runUnary (http://localhost:59940/dart_sdk.js:38889:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:59940/dart_sdk.js:33875:29)
    at handleValueCallback (http://localhost:59940/dart_sdk.js:34435:49)
    at Function._propagateToListeners (http://localhost:59940/dart_sdk.js:34473:17)
    at _Future.new.[_complete] (http://localhost:59940/dart_sdk.js:34307:25)
    at http://localhost:59940/dart_sdk.js:33440:30
    at internalCallback (http://localhost:59940/dart_sdk.js:25104:11)

**Comment by robinjanke** [comment]
I got thee exact same error...

**Comment by terrier989** [comment]
Hi! Thanks for the issue report! This has been fixed.

**Comment by Screendead** [comment]
I'm getting the same issue on ^2.0.4:

Error: UnimplementedError
    at Object.throw_ [as throw] (http://localhost:58560/dart_sdk.js:5031:11)
    at Function.new (http://localhost:58560/packages/universal_io/src/io/sync_socket.dart.lib.js:3652:19)
    at Function.fromRawPath (http://localhost:58560/packages/universal_io/src/io/sync_socket.dart.lib.js:3658:27)
    at convertEventCSV (http://localhost:58560/packages/app/widgets/vc_staff/csv_parser.dart.lib.js:100:29)
    at convertEventCSV.next (<anonymous>)
    at runBody (http://localhost:58560/dart_sdk.js:37228:34)
    at Object._async [as async] (http://localhost:58560/dart_sdk.js:37259:7)
    at Object.convertEventCSV (http://localhost:58560/packages/app/widgets/vc_staff/csv_parser.dart.lib.js:99:18)
    at event_uploader._EventUploaderState.new.<anonymous>
    (http://localhost:58560/packages/app/widgets/vc_staff/event_uploader.dart.lib.js:1951:59)
    at Generator.next (<anonymous>)
    at http://localhost:58560/dart_sdk.js:37209:33
    at _RootZone.runUnary (http://localhost:58560/dart_sdk.js:37080:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:58560/dart_sdk.js:32336:29)
    at handleValueCallback (http://localhost:58560/dart_sdk.js:32863:49)
    at Function._propagateToListeners (http://localhost:58560/dart_sdk.js:32901:17)
    at _Future.new.[_completeWithValue] (http://localhost:58560/dart_sdk.js:32749:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:58560/dart_sdk.js:32770:35)
    at Object._microtaskLoop (http://localhost:58560/dart_sdk.js:37332:13)
    at _startMicrotaskLoop (http://localhost:58560/dart_sdk.js:37338:13)
    at http://localhost:58560/dart_sdk.js:33109:9

**Comment by jtmuller5** [comment]
I have this same error as well.

**Comment by sakyoyuto** [comment]
I have same problem.
